on:
  pull_request:
name: Pylint checker test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      id: pylint-result
      continue-on-error: true
      run: |
        diff=$(git diff --name-only origin/main | grep "\.py$")
        res=$((pylint $diff || true) 2>&1 | tr "*" "-" | grep -v "Instance of 'Child' has no '.*' member")
        echo $res
        echo "PYLINT_RES<<EOF" >> $GITHUB_ENV
        echo "$res" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: pylint-result-comment
        message: |
          Pylint ran here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          <details><summary>Pylint Result</summary>
          <pre><code>${{ env.PYLINT_RES }}</code></pre>
          </details>