on:
  pull_request:
name: Pylint - checker
jobs:
  pylint-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-gi python3-gi-cairo gir1.2-gtk-3.0
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      id: pylint-result
      continue-on-error: true
      run: |
        mkdir -p output
        python3 utils/pylint-parser.py > output/pylint-result
        cat output/pylint-result
        echo ${{ github.event.number }} > output/pr-number
    - uses: actions/upload-artifact@v2
      with:
        name: pylint-result
        path: output/
